[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.5.5"
disjoint-sets = "0.4.2"
ndarray = "0.15.4"
union-find = "0.3.3"
